<a href="https://colab.research.google.com/github/mstep10/moo/blob/main/numpy_03a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy введение.  (MY)                      mms,11.09.22   *) + о точности sum/fsum/np.sum

https://numpy.org/doc/1.23/numpy-user.pdf  - подробно и с большим количеством примеров. На английском, но не сложно.
https://physics.susu.ru/vorontsov/language/numpy.html    -довольно полная информация справочная информация по библиотеке

In [ ]:
import numpy as np
#from numpy import *

#Создание массива(вектора) из списка
nums = [1, 3, -1]
v = np.array(nums,dtype=float)
print(type(v))
v

<class 'numpy.ndarray'>


array([ 1.,  3., -1.])

In [ ]:
v1=np.arange(1, 5)              #Cоздает вектор с элементами от 1 до 4
#Cравните вывод:
print(v1)
print(*v1)
v1

[1 2 3 4]
1 2 3 4


array([1, 2, 3, 4])

In [ ]:
# Создаем двумерный массив
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10], [9,10,11]])
print(M[0, 1])
M[0,1]=100          #Изменение элемента массива
M

2


array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,  10],
       [  9,  10,  11]])

In [ ]:
print(M.size)     # число элементов в массиве
print(M.ndim)     # размерность массива
print(M.shape)    # кортеж с размером каждого измерения массива
print(len(M))     # длина по первой оси

12
2
(4, 3)
4


In [ ]:
#Все элементы в массиве numpy принадлежат одному типу
x = np.array([1.0, 2.0])   # Автоматический выбор типа
print(x.dtype)

x = np.array([1.0, 2.0], dtype=np.int32)   # Принудительное задание типа
print(x.dtype)

float64
int32


In [ ]:
b = np.eye(4)
print ("Единичная матрица:\n", b)

c = np.ones((2, 5))
print ("Матрица из всех единиц:\n", c)

z = np.zeros((3, 3))
print ("Матрица из всех нулей:\n", c)


Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Матрица из всех единиц:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Матрица из всех нулей:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
v2 = np.arange(0, 24, 2)
print ("Вектор-столбец:\n", v2)

d = v2.reshape((3, 4))     #!функция reshape создает новый массив, исходный массив v2 она не изменяет
print ("Матрица:\n", d)


Вектор-столбец:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]
Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [ ]:
# Как создать одномерную версию многомерного массива?
d.flatten()

#d.flatten().tolist()   # а это преобразование массива в список

In [ ]:
d = np.full((2,2), 7)  # Создает матрицу 2x2 заполненую заданным значением 7
print(d)

e = np.random.random((2,2))   # cоздает матрицу заполненую случаными числами из интервала (0, 1)
print(e)

f=np.random.randint(1,4,10).reshape(2,5)    # cоздает матрицу 2x5 заполненую случаными числами из интервала [1, 4)
print(f)

In [ ]:
np.random.

In [ ]:
#Cрезы.
# В качестве упражнения попробуйте определить результат каждой строки,
# а потом проверьте, сняв комментарий

print(M)
M[:, 1]
#M[0:2, 1]
#M[0:-1, 1]
#M[1]
#M[:, [0,2]]

#print(v)
#M[0, :] = v  # меняет первую строку в массиве на элменты вектора v
#M

[[  1 100   3]
 [  4   5   6]
 [  7   8  10]
 [  9  10  11]]


array([100,   5,   8,  10])

In [ ]:
#Базовые методы
A = np.array([2,3,4], dtype=np.float64)
print(A.sum())
print(A.prod())
print(A.mean())
print(A.max())
print(A.argmin())  #argmin и argmax возвращают индексы массива минимума и максимума

# Большинство приведенных выше методов можно вызывать и как обычные функции:
print(sum(A))
print(min(A))

#Для многомерных массивов каждая из этих функций может принимать необязательный
#параметр axis (ось аргумента), и тогда будет выполнять операцию только по указанной оси.
B = np.array([[1, 3], [3, -1], [5, 7]], dtype=np.float64)
print('B=',B)
B.mean(axis=1)

In [ ]:
# Операции над массивами.
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
print(M)
print(v)
#M+M                  #поэлеметное сложение
#M*M                  #поэлеметное(!) умножение
#M*v
#np.sin(M)            #поэлементное применение функции sin

np.dot(M, M)         #матричное умножение

#np.trace(M)          #cумма диагональных элеменов
#np.diagonal(M)       #извлечь диагональные элементы
#np.linalg.det(M)     #определитель

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[ 1.  3. -1.]


array([[ 30,  36,  45],
       [ 66,  81, 102],
       [109, 134, 169]])

In [ ]:
#Решение системы линейных уравнений Mx=y. (Построим у для x=v и проверим, что найденное решение совпадет с v)
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
v = np.array([1, 3, -1])
y = np.dot(M, v)
print(y)
x=np.linalg.solve(M, y)     # используется решатель linalg.solve
x

In [ ]:
#Итерации как и для списков
A = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)
for x in A:
   print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [ ]:
# Cкорость обработки массивов намного выше, чем списков.
# Пример: посчитаем сумму квадратных корней первых 10^7 чисел и посмотрим различие в скорости работы массивов и списков.

from time import time
from math import sqrt,fsum

t = time()
print(f"Результат итера0: {sum(x ** 0.5 for x in range(10 ** 7))}.")
print(f"{time() - t} с.")

t = time()
print(f"Результат итераf: {fsum(sqrt(x) for x in range(10 ** 7))}.")
print(f"{time() - t} с.")

t = time()
print(f"Результат numpy1: {sum(np.sqrt(np.arange(10 ** 7)))}.")
##print(f"Результат numpy: {np.sqrt(np.arange(10 ** 7)).sum()}.")
print(f"{time() - t} с.")

t = time()
print(f"Результат numpy2: {(np.sqrt(np.arange(10 ** 7))).sum()}.")
print(f"{time() - t} с.")

##np.array_equal(a, b)

Результат итера0: 21081849486.439312.
1.1174812316894531 с.
Результат итераf: 21081849486.442493.
1.3276031017303467 с.
Результат numpy1: 21081849486.439312.
0.7536470890045166 с.
Результат numpy2: 21081849486.442448.
0.04662275314331055 с.


In [ ]:
# Замечание о точности.
# Для чисел с плавающей запятой числовая точность суммы в целом ограничена прямым добавлением каждого
# числа по отдельности к результату, что вызывает ошибки округления на каждом шаге.
# 1) fsum из библиотеки math лучше, чем sum работает с числами с плавающей запятой.
# 2) функции sum() и np.sum() не идентичны. Так, смысл их опциональных
# аргументов отличается и функция np.sum() может работать с многомерными массивами
# np.sum из numpy может использовать численно лучший подход (частичное попарное суммирование),

from math import fsum

print(sum([.1, .1, .1, .1, .1, .1, .1, .1, .1, .1]))      # 0.9999999999999999
print(fsum([.1, .1, .1, .1, .1, .1, .1, .1, .1, .1]))     # 1.0


0.9999999999999999
1.0


In [ ]:

#Важно заметить, что функции sum() и np.sum() не идентичны. Так, смысл их опциональных
#аргументов отличается и функция np.sum() может работать с многомерными массивами

big_array = np.random.rand(1000000)
%timeit s=sum(big_array)         # Магическая команда в IPython
%timeit ns=np.sum(big_array)
%timeit ns1=big_array.sum()
s=sum(big_array)
ns=np.sum(big_array)
ns1=big_array.sum()
print(s)
print(ns)
print(ns1)

76.7 ms ± 256 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
573 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
571 µs ± 5.25 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
500198.4140149663
500198.414014964
500198.414014964


In [ ]:
#Вместе со стандартным набором математических функций numpy содержит две константы
print(np.pi, np.e)

In [ ]:
#O копировании
print(M)
C = M[1:3, 1:3]
print(C)
C[1:] =100
print(C)
print(M)
#C = M[1:3, 1:3].copy()    - а правильно было так!

In [ ]:
#Транспонирование
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [ ]:
#Ранг матрицы (мах число независимых строк столбцов)
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)
print(r)

In [ ]:
#Обратите внимание: вектор (одномерный массив) и вектор-столбец или вектор-строка (двумерные массивы)
#являются различными объектами в NumPy, хотя математически задают один и тот же объект.
#В случае одномерного массива shape состоит из одного числа и имеет вид (n,), где n — длина вектора.
#В случае двумерных векторов в shape присутствует еще одна размерность (n,1).
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print (f'a:\n {a}\n {a.shape}')
print (f'b:\n {b}\n {b.shape}\n')

#В большинстве случаев неважно, какое представление использовать, потому что часто
#срабатывает приведение типов. Но некоторые операции не работают для одномерных массивов.
#Например, транспонирование:
print(a.T)
print(b,b.T)


a:
 [1 2 3]
 (3,)
b:
 [[1]
 [2]
 [3]]
 (3, 1)

[1 2 3]
[[1]
 [2]
 [3]] [[1 2 3]]


In [ ]:
#Норма
#linalg.norm(a[, ord])
a = np.array([2, 2, -3])
print('L1 норма вектора a:', np.linalg.norm(a, ord=1))
print('L2 норма вектора a:', np.linalg.norm(a, ord=2))

In [ ]:
#Обратная матрица(для квадратных невырожденных матриц)
A = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
D = np.array([[1, 2, 1], [1, 1, 4], [1, 8, 4], [2, 3, 6]], dtype=np.float32)
D
print(np.linalg.inv(A))
print(np.linalg.pinv(D))     #Псевдо-обратная матрица (Мура-Пенроуза) для произвольных матриц

[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
[[ 1.1455742  -0.36210677 -0.34674472  0.28163862]
 [ 0.0380395  -0.06949525  0.14557424 -0.05705925]
 [-0.3650329   0.22457936  0.04535479  0.04754937]]


In [ ]:
np.linalg.eig(A) 	    #собственные значения и собственные вектора квадратной матрицы

(array([ 8.345132  ,  0.21422778, -0.5593595 ], dtype=float32),
 array([[-0.24707341, -0.9428197 ,  0.774807  ],
        [-0.4891597 ,  0.280078  , -0.6300621 ],
        [-0.83646727,  0.18068555,  0.05192159]], dtype=float32))

In [ ]:
#Cоздание сеток
#Равномерный набор заданного числа точек(11) на заданном интрвале [-5,5]
x = np.linspace(-5, 5, 11)
print(x)

#Набор последовательных чисел из промежутка [start, stop) с заданным шагом step
#arange([start,] stop [, step,][, dtype])
x=np.arange(4.0)
print(x)

#Логарифмический набор точек
x=np.logspace(2.0, 3.0, num=4, base=2.0)
print(x)

#Два вектора, описывающих точки ортогональной сетки.
X, Y = np.meshgrid([1,2,3], [4,5,7])

In [ ]:
# Постейший вариант сохранения и чтения массива из файла
data = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt("data.txt", data, delimiter=",")
data = np.loadtxt("data.txt", delimiter=",", dtype=np.int32)
print(data)

In [ ]:
#Задания

#Заданиe_1
#Создайте вектор из нулей длины 12, но его 4-й елемент должен быть равен 1

#Заданиe_2
#Создайте матрицу (3, 3), заполненую от 0 до 8

#Задание_3
#Напишите функцию, которая принимает размер матрицы, а возвращает матрицу,
#сформированною ее по формуле
#A[n,m] = n + 10 * m

#Заданиe_4
#Создайте рандомный вектор и отсортируйте его по убыванию.(Найдите и разберитесь
#с функцией сортировки)

#Заданиe_5
#Напишите свои функции вычисления L1 и L2 нормы вектора и сравните с np.linalg.norm.
#Для каждой нормы напечатайте в строку оба значения и результат сравнения.
#Оформите все в виде функции с одним аргументом(входным вектором).

#Задание_6
#Напишите функцию, принимающую на вход два вектора, которая вычисляет
#угол между этими векторами.

#Задание_7
#Сгенерируйте матрицу 4x4 из целых случайных чисел.
#Если определитель матрицы не равен 0, то вычислите обратную матрицу.
#Проверьте, что произведение A на обратную должна быть единичной.

#Заданиe_8
#Написать функцию select_even(arr), принимающую на вход массив целых чисел arr
#и возвращающую новый массив, который состоит из всех чётных элементов arr.

#Задание_9
#Сгенериуйте две матрицы 1000 х 1000 из случайнах целых чисел от 0 до 10.
#Сравним быстродействие обычной реализации поэлементного сложения матриц через цикл
#и метода NumPy.  А также проверьте, совпадают ли результаты.

#Заданиe_10
#Написать функцию wipe_even(arr, target_value, in_place), принимающую на вход массив целых
#чисел arr, и возвращающую массив, полученный из arr путём замены всех чётных элементов на
#target_value. Если target_value не указано, то оно должно считаться равным числу 0.
#Если указан параметр in_place и он равен True, то функция должна менять исходный массив,
#а если не указан или указан в False, то сохранять его неизменным.

#Заданиe_11
#Постройте 3D-график функции z=x^2-y^2 на области x: [-1.5, 1.5], y: [-1,1]